const products = [
  { id: "1", name: "Đầm yếm trắng", price: "459.000đ", description: "Thiết kế cổ yếm quyến rũ, ôm sát cơ thể, chất liệu cao cấp thoáng mát.", category: ["Nữ", "Váy"], image: "img/sp1.jpg" },
  { id: "2", name: "Set croptop đỏ đen", price: "529.000đ", description: "Cá tính, trẻ trung, phối hợp đỏ đen hiện đại, chất vải đứng form.", category: ["Nữ", "Váy"], image: "img/sp2.jpg" },
  { id: "3", name: "Đầm suông trắng tay dài", price: "479.000đ", description: "Đầm trắng thanh lịch, tay dài che khuyết điểm, cực phù hợp đi làm, đi chơi.", category: ["Nữ", "Váy"], image: "img/sp3.jpg" },
  { id: "4", name: "Váy dạ hội ren đen", price: "549.000đ", description: "Phong cách sang trọng, phối ren tinh tế, phù hợp sự kiện & tiệc tối.", category: ["Nữ", "Váy"], image: "img/sp4.jpg" },
  { id: "5", name: "Đầm công chúa tay bồng", price: "569.000đ", description: "Phong cách công chúa hiện đại, tay bồng dễ thương, tạo nét nhẹ nhàng.", category: ["Nữ", "Váy"], image: "img/sp5.jpg" },
  { id: "6", name: "Đầm trắng cổ V", price: "519.000đ", description: "Cổ V quyến rũ, dáng xòe vừa phải, dễ mặc cho nhiều dịp.", category: ["Nữ", "Váy"], image: "img/sp6.jpg" },
  { id: "7", name: "Twin Set trắng đen", price: "599.000đ", description: "Set đồ đôi trắng đen cá tính, dành cho bạn thân hoặc chị em mix match.", category: ["Nữ", "Váy"], image: "img/sp7.jpg" },
  { id: "8", name: "Váy maxi xếp tầng", price: "449.000đ", description: "Thiết kế xếp tầng bồng bềnh, thích hợp cho chuyến du lịch mùa hè.", category: ["Nữ", "Váy"], image: "img/sp8.jpg" },
  { id: "9", name: "Váy 2 dây trắng kem", price: "429.000đ", description: "Kiểu dáng nhẹ nhàng, thanh lịch, bo eo tôn dáng tự nhiên.", category: ["Nữ", "Váy"], image: "img/sp9.jpg" },
  { id: "10", name: "Váy cưới trắng đơn giản", price: "749.000đ", description: "Tối giản, thanh lịch, cực phù hợp cho tiệc cưới hoặc concept chụp hình.", category: ["Nữ", "Váy"], image: "img/sp10.jpg" },
  { id: "11", name: "Áo sơ mi trắng nam", price: "329.000đ", description: "Áo sơ mi trắng cổ điển, thanh lịch cho môi trường công sở hoặc sự kiện.", category: ["Nam", "Áo"], image: "img/sp11.jpg" },
  { id: "12", name: "Áo sơ mi đen phối trắng", price: "369.000đ", description: "Form chuẩn nam tính, phối màu hiện đại, dễ mix đồ.", category: ["Nam", "Áo"], image: "img/sp12.jpg" },
  { id: "13", name: "Áo polo trắng cổ viền", price: "289.000đ", description: "Phong cách thể thao sang trọng, cổ viền tinh tế, dễ kết hợp.", category: ["Nam", "Áo"], image: "img/sp13.jpg" },
  { id: "14", name: "Áo polo trắng", price: "489.000đ", description: "Thiết kế lửng năng động, chất vải mềm mịn, phù hợp mùa thu đông.", category: ["Nam", "Áo"], image: "img/sp14.jpg" },
  { id: "15", name: "Áo nữ tay lỡ", price: "339.000đ", description: "Phù hợp công sở, form nhẹ nhàng, dễ phối với chân váy hoặc quần.", category: ["Nữ", "Áo"], image: "img/sp15.jpg" },
  { id: "16", name: "Áo blouse bèo nhún", price: "359.000đ", description: "Phong cách cổ điển, bèo nhún nhẹ nhàng tạo nét thanh lịch.", category: ["Nữ", "Áo"], image: "img/sp16.jpg" },
  { id: "17", name: "Váy Xuông", price: "419.000đ", description: "Thiết kế suông đứng, tôn dáng mạnh mẽ, chất liệu thoáng mát.", category: ["Nữ", "Váy"], image: "img/sp17.jpg" },
  { id: "18", name: "Váy Ngủ", price: "439.000đ", description: "Phong cách cổ điển pha hiện đại, phù hợp đi làm, sự kiện.", category: ["Nữ", "Váy"], image: "img/sp18.jpg" },
  { id: "19", name: "Quần Tây Nam Trắng Ôm", price: "389.000đ", description: "Tôn dáng nhẹ nhàng, chất liệu mềm mại, mặc cả ngày thoải mái.", category: ["Nam", "Quần"], image: "img/sp19.jpg" },
  { id: "20", name: "Váy Ngủ", price: "459.000đ", description: "Cá tính, thời thượng, chất denim cao cấp, kiểu dáng hiện đại.", category: ["Nữ", "Váy"], image: "img/sp20.jpg" },
  { id: "21", name: "Áo Liền Thân Nữ", price: "299.000đ", description: "Phong cách tối giản, thích hợp cho các hoạt động ngoài trời.", category: ["Nữ", "Áo"], image: "img/sp21.jpg" },
  { id: "22", name: "Áo Ngủ Ren", price: "399.000đ", description: "Thiết kế gọn nhẹ, thời trang cho những ngày gió se lạnh.", category: ["Nữ", "Áo"], image: "img/sp22.jpg" },
  { id: "23", name: "Áo sơ mi đen", price: "279.000đ", description: "Croptop trẻ trung, tôn eo, phù hợp với phong cách năng động.", category: ["Nam", "Áo"], image: "img/sp23.jpg" },
  { id: "24", name: "Áo sơ mi trắng", price: "259.000đ", description: "Thoải mái, mát mẻ, phù hợp mặc trong mùa hè hoặc đi biển.", category: ["Nam", "Áo"], image: "img/sp24.jpg" },
  { id: "25", name: "Áo thun trắng form rộng", price: "309.000đ", description: "Form rộng thoải mái, unisex, dễ phối đồ hàng ngày.", category: ["Nam", "Áo"], image: "img/sp25.jpg" },
  { id: "26", name: "Áo thun oversize", price: "239.000đ", description: "Năng động, co giãn tốt, thích hợp cho tập gym hoặc yoga.", category: ["Nam", "Áo"], image: "img/sp26.jpg" },
  { id: "27", name: "Quần Tây", price: "469.000đ", description: "Sang trọng, bay bổng, dễ kết hợp với áo sơ mi hoặc croptop.", category: ["Nam", "Quần"], image: "img/sp27.jpg" },
  { id: "28", name: "Quần Âu", price: "599.000đ", description: "Phong cách tinh tế, nhẹ nhàng, chất lượng cao cấp tạo sự sang trọng.", category: ["Nam", "Quần"], image: "img/sp28.jpg" }
];